spring:
  application:
    name: transfer-batch
  datasource:
    platform: postgres
    username: ${DB_USER:batch_user}
    password: ${DB_PASSWORD:batch_password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transfer_batch}?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
    contexts: ${CHANGE_LOG:dev}
    user: ${DB_USER:batch_user}
    password: ${DB_PASSWORD:batch_password}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: ${PORT:8086}